fine_tune_params:
  batch_size: 4
  epochs: 10
  iteration: 100
  learning_rate: 1e-5
  weight_decay: 4e-5
  trainable_image_encoder: false
  trainable_mask_decoder: true
  trainable_prompt_encoder: true

model:
  checkpoint: "/content/SA307/SAM2/sam2_hiera_large.pt" 
  config : "configs/sam2/sam2_hiera_l.yaml" 
  device: cuda

fine_tune_path:
  train_dir: "/kaggle/input/loveda-307/train_v5/images_png"
  train_dir_mask: "/kaggle/input/loveda-307/train_v5/masks_png"
  val_dir: "/kaggle/input/loveda-307/val_v5/images_png"
  val_dir_mask: "/kaggle/input/loveda-307/val_v5/masks_png"
  logs: "/content/SA307/fine-tune/logs"
  metric: "/content/SA307/fine-tune/metric"

testing:
  test_dir: "/content/drive/Shareddrives/TA/Bimbingan/test_v5/images_png"
  test_dir_mask: "/content/drive/Shareddrives/TA/Bimbingan/test_v5/masks_png"
  test_dir_output: "/path/to/output"
  test_dir_all_mask: "/kaggle/input/loveda-307/test_v5/all_masks_png"
  predict_out : "/content/predict_out"
  visual_out : "/content/visual_out"
  excel_out : "/content/test_excel"
  number_runs : 5

datasets:
  annotatation_coco: "/path/to/annotations"

variant_mapping:
  checkpoint_tiny: "/content/SA307/SAM2/sam2_hiera_tiny.pt" 
  config_tiny: "sam2_hiera_t.yaml" 
  checkpoint_small: "/content/SA307/SAM2/sam2_hiera_small.pt" 
  config_small: "sam2_hiera_s.yaml" 
  checkpoint_base: "/content/SA307/SAM2/sam2_hiera_base_plus.pt" 
  config_base: "sam2_hiera_b+.yaml" 
  checkpoint_large: "/content/SA307/SAM2/sam2_hiera_large.pt" 
  config_large: "sam2_hiera_l.yaml" 
  device: cuda

checkpoint_path:
    c_tiny: "/content/model/fine_tune_tiny_10epoch.pth"
    c_small: "/content/model/fine_tune_small_10epoch.pth"
    c_base: "/content/model/fine_tune_baseplus_10epoch.pth"
    c_large: "/content/model/fine_tune_10epoch_2_2.pth"